global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'microservices'
    static_configs:
      - targets:
          - 'auth_service:4242'
          - 'catalog:8001'
          - 'orders_service:8002'
          - 'reviews:8000'

  - job_name: 'redis'
    static_configs:
      - targets:
          - 'redis-exporter:9121'

  - job_name: 'kafka'
    static_configs:
      - targets:
          - 'kafka-exporter:9308'