"""Initial

Revision ID: 21e9700fed61
Revises:
Create Date: 2025-05-10 16:50:17.868955

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "21e9700fed61"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exchange_rates",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("currency", sa.String(length=10), nullable=False),
        sa.Column("rate", sa.Float(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("exchange_rates")
    # ### end Alembic commands ###
