"""put_estimated_cost

Revision ID: ce3a96c2cd2e
Revises: 583570ebaec6
Create Date: 2025-05-10 21:14:09.599871

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "ce3a96c2cd2e"
down_revision = "583570ebaec6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("estimated_cost", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "estimated_cost")
    # ### end Alembic commands ###
