{
 "title": "catalog_service",
 "tags": [
  "fastapi",
  "prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m]))",
     "legendFormat": "All Requests"
    }
   ]
  },
  {
   "title": "Latency (avg by endpoint)",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "rate(latency_seconds_sum[1m]) / rate(latency_seconds_count[1m])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "4xx Errors",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=~\"4..\"}[1m]))",
     "legendFormat": "4xx"
    }
   ]
  },
  {
   "title": "5xx Errors",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=~\"5..\"}[1m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Requests by Endpoint (per minute)",
   "type": "table",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by (endpoint)(rate(http_requests_total[1m]))"
    }
   ]
  }
 ]
}