"""add cascade delete

Revision ID: e84eb4dedeba
Revises: ee382fa2ced9
Create Date: 2025-04-02 15:55:00.538963

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e84eb4dedeba"
down_revision = "ee382fa2ced9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("products_category_id_fkey", "products", type_="foreignkey")
    op.create_foreign_key(
        None, "products", "categories", ["category_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "products", type_="foreignkey")
    op.create_foreign_key(
        "products_category_id_fkey", "products", "categories", ["category_id"], ["id"]
    )
    # ### end Alembic commands ###
